name: Build Linux Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxcb-cursor0  # fix Qt errors
          pip install pyinstaller -r requirements.txt
          python -c "from imageio_ffmpeg import get_ffmpeg_exe; print(get_ffmpeg_exe())"

      - name: Get FFmpeg path
        id: ffmpeg
        run: |
          echo "ffmpeg=$(python -c 'from imageio_ffmpeg import get_ffmpeg_exe; print(get_ffmpeg_exe())')" >> $GITHUB_OUTPUT

      - name: Build executable
        run: |
          pyinstaller main.py --onefile --add-binary "${{ steps.ffmpeg.outputs.ffmpeg }}:."

      - name: Debugging - List dist directory
        run: ls -R dist

      - uses: actions/upload-artifact@v3
        with:
          name: linux-exe
          path: dist/main