name: Build PyQt5 HLS Converter (Manual FFmpeg)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build for Linux
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Download FFmpeg
        run: |
          wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
          tar -xf ffmpeg-release-amd64-static.tar.xz
          sudo cp ffmpeg-*-amd64-static/ffmpeg /usr/local/bin/
          sudo chmod +x /usr/local/bin/ffmpeg
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Build Linux executable with manual FFmpeg
        run: |
          pyinstaller main.py \
            --name hls-converter-linux \
            --onefile \
            --noconfirm \
            --hidden-import=sip \
            --add-binary="/usr/local/bin/ffmpeg:."
            
      - name: Upload Linux Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hls-converter-linux
          path: dist/hls-converter-linux

  build-windows:
    runs-on: windows-latest
    name: Build for Windows
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Download FFmpeg for Windows
        run: |
          Invoke-WebRequest -Uri "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip" -OutFile "ffmpeg.zip"
          Expand-Archive -Path "ffmpeg.zip" -DestinationPath "."
          $ffmpegPath = Get-ChildItem -Path "." -Name "ffmpeg-*" -Directory | Select-Object -First 1
          Copy-Item -Path "$ffmpegPath/bin/ffmpeg.exe" -Destination "ffmpeg.exe"
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Build Windows executable with manual FFmpeg
        run: |
          pyinstaller main.py --name hls-converter-windows --onefile --windowed --noconfirm --add-binary="ffmpeg.exe;."
          
      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hls-converter-windows
          path: dist/hls-converter-windows.exe